"use strict";

var topics = [
{
"jobtitle": "Junior Front-End Developer",
"company": "LaunchCode",
"city": "Miami",
"state": "FL",
"country": "US",
"formattedLocation": "Miami, FL",
"source": "LaunchCode",
"date": "Tue, 03 Nov 2015 04:05:49 GMT",
"snippet": "Ample experience navigating Photoshop and saving images for the <b>web</b>. We place you with an experienced <b>developer</b> from whom you can learn....",
"url": "http://www.indeed.com/viewjob?jk=1a807de3d5a81974&qd=_Eg2vwv-W7Xbq1qTFtzNjBoBOJ1n8jtnz2g86skcQrONeGbI_vQ-GttizbVSNLPf-ObBmLC0o-SFavhdY8sjrQA8LVfuFZ7NGBUNW0PNydwkt0LCVy_rQinuMfW47e_m&indpubnum=1588917421720308&atk=1a3j9gtcm5t9ldfh",
"onmousedown": "indeed_clk(this, '2655');",
"latitude": 25.771978,
"longitude": -80.19231,
"jobkey": "1a807de3d5a81974",
"sponsored": false,
"expired": false,
"indeedApply": false,
"formattedLocationFull": "Miami, FL",
"formattedRelativeTime": "5 days ago"
},
{
"jobtitle": "Front End Developer",
"company": "CALLPAL APP",
"city": "Miami",
"state": "FL",
"country": "US",
"formattedLocation": "Miami, FL",
"source": "Indeed",
"date": "Thu, 05 Nov 2015 16:34:59 GMT",
"snippet": "Our team is growing fast and we are seeking for Front End <b>Developers</b> to join the team:. This includes all UI programming in AngularJS as well as all front end...",
"url": "http://www.indeed.com/viewjob?jk=3f59fbe4d502dd38&qd=_Eg2vwv-W7Xbq1qTFtzNjBoBOJ1n8jtnz2g86skcQrONeGbI_vQ-GttizbVSNLPf-ObBmLC0o-SFavhdY8sjrQA8LVfuFZ7NGBUNW0PNydwkt0LCVy_rQinuMfW47e_m&indpubnum=1588917421720308&atk=1a3j9gtcm5t9ldfh",
"onmousedown": "indeed_clk(this, '2655');",
"latitude": 25.782967,
"longitude": -80.19231,
"jobkey": "3f59fbe4d502dd38",
"sponsored": false,
"expired": false,
"indeedApply": true,
"formattedLocationFull": "Miami, FL 33132",
"formattedRelativeTime": "2 days ago"
},
{
"jobtitle": "Web Designer/Developer & Graphic",
"company": "CosmoFrance.net",
"city": "Miami",
"state": "FL",
"country": "US",
"formattedLocation": "Miami, FL",
"source": "Indeed",
"date": "Fri, 06 Nov 2015 16:12:32 GMT",
"snippet": "We're looking for a <b>web</b> &amp; graphic designer to design and/or re-design our product websites, as well as brochures, , email newsletters &amp; other marketing material...",
"url": "http://www.indeed.com/viewjob?jk=efcd23b23e721570&qd=_Eg2vwv-W7Xbq1qTFtzNjBoBOJ1n8jtnz2g86skcQrONeGbI_vQ-GttizbVSNLPf-ObBmLC0o-SFavhdY8sjrQA8LVfuFZ7NGBUNW0PNydwkt0LCVy_rQinuMfW47e_m&indpubnum=1588917421720308&atk=1a3j9gtcm5t9ldfh",
"onmousedown": "indeed_clk(this, '2655');",
"latitude": 25.782967,
"longitude": -80.19231,
"jobkey": "efcd23b23e721570",
"sponsored": false,
"expired": false,
"indeedApply": true,
"formattedLocationFull": "Miami, FL 33132",
"formattedRelativeTime": "1 day ago"
},
{
"jobtitle": "Junior Front-End Developer",
"company": "LaunchCode",
"city": "Palm Beach",
"state": "FL",
"country": "US",
"formattedLocation": "Palm Beach, FL",
"source": "LaunchCode",
"date": "Tue, 03 Nov 2015 04:05:45 GMT",
"snippet": "Ample experience navigating Photoshop and saving images for the <b>web</b>. We place you with an experienced <b>developer</b> from whom you can learn....",
"url": "http://www.indeed.com/viewjob?jk=a0441eac1967a5d3&qd=_Eg2vwv-W7Xbq1qTFtzNjBoBOJ1n8jtnz2g86skcQrONeGbI_vQ-GttizbVSNLPf-ObBmLC0o-SFavhdY8sjrQA8LVfuFZ7NGBUNW0PNydwkt0LCVy_rQinuMfW47e_m&indpubnum=1588917421720308&atk=1a3j9gtcm5t9ldfh",
"onmousedown": "indeed_clk(this, '2655');",
"latitude": 26.703297,
"longitude": -80.03297,
"jobkey": "a0441eac1967a5d3",
"sponsored": false,
"expired": false,
"indeedApply": false,
"formattedLocationFull": "Palm Beach, FL",
"formattedRelativeTime": "5 days ago"
},
{
"jobtitle": "Junior Front-End Developer",
"company": "LaunchCode",
"city": "Boca Raton",
"state": "FL",
"country": "US",
"formattedLocation": "Boca Raton, FL",
"source": "LaunchCode",
"date": "Tue, 03 Nov 2015 04:05:44 GMT",
"snippet": "Ample experience navigating Photoshop and saving images for the <b>web</b>. We place you with an experienced <b>developer</b> from whom you can learn....",
"url": "http://www.indeed.com/viewjob?jk=1a7253290290024f&qd=_Eg2vwv-W7Xbq1qTFtzNjBoBOJ1n8jtnz2g86skcQrONeGbI_vQ-GttizbVSNLPf-ObBmLC0o-SFavhdY8sjrQA8LVfuFZ7NGBUNW0PNydwkt0LCVy_rQinuMfW47e_m&indpubnum=1588917421720308&atk=1a3j9gtcm5t9ldfh",
"onmousedown": "indeed_clk(this, '2655');",
"latitude": 26.357143,
"longitude": -80.08242,
"jobkey": "1a7253290290024f",
"sponsored": false,
"expired": false,
"indeedApply": false,
"formattedLocationFull": "Boca Raton, FL",
"formattedRelativeTime": "5 days ago"
},
{
"jobtitle": "Junior Front-End Developer",
"company": "LaunchCode",
"city": "Fort Lauderdale",
"state": "FL",
"country": "US",
"formattedLocation": "Fort Lauderdale, FL",
"source": "LaunchCode",
"date": "Tue, 03 Nov 2015 04:05:43 GMT",
"snippet": "Ample experience navigating Photoshop and saving images for the <b>web</b>. We place you with an experienced <b>developer</b> from whom you can learn....",
"url": "http://www.indeed.com/viewjob?jk=b7e77f9597b106a5&qd=_Eg2vwv-W7Xbq1qTFtzNjBoBOJ1n8jtnz2g86skcQrONeGbI_vQ-GttizbVSNLPf-ObBmLC0o-SFavhdY8sjrQA8LVfuFZ7NGBUNW0PNydwkt0LCVy_rQinuMfW47e_m&indpubnum=1588917421720308&atk=1a3j9gtcm5t9ldfh",
"onmousedown": "indeed_clk(this, '2655');",
"latitude": 26.120878,
"longitude": -80.14286,
"jobkey": "b7e77f9597b106a5",
"sponsored": false,
"expired": false,
"indeedApply": false,
"formattedLocationFull": "Fort Lauderdale, FL",
"formattedRelativeTime": "5 days ago"
},
{
"jobtitle": "Full Stack Developer",
"company": "CALLPAL APP",
"city": "Miami",
"state": "FL",
"country": "US",
"formattedLocation": "Miami, FL",
"source": "Indeed",
"date": "Thu, 05 Nov 2015 16:36:50 GMT",
"snippet": "Our team is growing fast and we are seeking a full stack <b>developer</b> to help in the creation and maintenance of our various websites....",
"url": "http://www.indeed.com/viewjob?jk=64871c211a4b31d8&qd=_Eg2vwv-W7Xbq1qTFtzNjBoBOJ1n8jtnz2g86skcQrONeGbI_vQ-GttizbVSNLPf-ObBmLC0o-SFavhdY8sjrQA8LVfuFZ7NGBUNW0PNydwkt0LCVy_rQinuMfW47e_m&indpubnum=1588917421720308&atk=1a3j9gtcm5t9ldfh",
"onmousedown": "indeed_clk(this, '2655');",
"latitude": 25.782967,
"longitude": -80.19231,
"jobkey": "64871c211a4b31d8",
"sponsored": false,
"expired": false,
"indeedApply": true,
"formattedLocationFull": "Miami, FL 33132",
"formattedRelativeTime": "2 days ago"
},
{
"jobtitle": "Web Developer",
"company": "Regis HRG",
"city": "Hialeah",
"state": "FL",
"country": "US",
"formattedLocation": "Hialeah, FL",
"source": "Indeed",
"date": "Tue, 27 Oct 2015 16:26:55 GMT",
"snippet": "You're into <b>web</b> development. One of our clients is hiring a *<b>Web</b> <b>Developer</b>*. You're into <b>web</b> technology and have a decent eye for what looks good....",
"url": "http://www.indeed.com/viewjob?jk=5f254d89720d8322&qd=_Eg2vwv-W7Xbq1qTFtzNjBoBOJ1n8jtnz2g86skcQrONeGbI_vQ-GttizbVSNLPf-ObBmLC0o-SFavhdY8sjrQA8LVfuFZ7NGBUNW0PNydwkt0LCVy_rQinuMfW47e_m&indpubnum=1588917421720308&atk=1a3j9gtcm5t9ldfh",
"onmousedown": "indeed_clk(this, '2655');",
"latitude": 25.901098,
"longitude": -80.3022,
"jobkey": "5f254d89720d8322",
"sponsored": false,
"expired": false,
"indeedApply": true,
"formattedLocationFull": "Hialeah, FL 33014",
"formattedRelativeTime": "11 days ago"
},
{
"jobtitle": "Junior Java Developer",
"company": "LaunchCode",
"city": "Miami",
"state": "FL",
"country": "US",
"formattedLocation": "Miami, FL",
"source": "LaunchCode",
"date": "Tue, 03 Nov 2015 04:05:46 GMT",
"snippet": "Some experience in developing <b>web</b> applications using at least one popular <b>web</b> framework (JSF, Wicket, GWT, Spring MVC)....",
"url": "http://www.indeed.com/viewjob?jk=416900b2b766c790&qd=_Eg2vwv-W7Xbq1qTFtzNjBoBOJ1n8jtnz2g86skcQrONeGbI_vQ-GttizbVSNLPf-ObBmLC0o-SFavhdY8sjrQA8LVfuFZ7NGBUNW0PNydwkt0LCVy_rQinuMfW47e_m&indpubnum=1588917421720308&atk=1a3j9gtcm5t9ldfh",
"onmousedown": "indeed_clk(this, '2655');",
"latitude": 25.771978,
"longitude": -80.19231,
"jobkey": "416900b2b766c790",
"sponsored": false,
"expired": false,
"indeedApply": false,
"formattedLocationFull": "Miami, FL",
"formattedRelativeTime": "5 days ago"
},
{
"jobtitle": "Lead Front-End Developer",
"company": "HYP3R",
"city": "Miami",
"state": "FL",
"country": "US",
"formattedLocation": "Miami, FL",
"source": "HYP3R",
"date": "Tue, 27 Oct 2015 10:17:33 GMT",
"snippet": "Analyzing and enhancing our <b>web</b> application performance. Experience with responsive and <b>web</b> mobile optimization techniques....",
"url": "http://www.indeed.com/viewjob?jk=79bf5558e5ba9541&qd=_Eg2vwv-W7Xbq1qTFtzNjBoBOJ1n8jtnz2g86skcQrONeGbI_vQ-GttizbVSNLPf-ObBmLC0o-SFavhdY8sjrQA8LVfuFZ7NGBUNW0PNydwkt0LCVy_rQinuMfW47e_m&indpubnum=1588917421720308&atk=1a3j9gtcm5t9ldfh",
"onmousedown": "indeed_clk(this, '2655');",
"latitude": 25.771978,
"longitude": -80.19231,
"jobkey": "79bf5558e5ba9541",
"sponsored": false,
"expired": false,
"indeedApply": true,
"formattedLocationFull": "Miami, FL",
"formattedRelativeTime": "11 days ago"
},
{
"jobtitle": "Web Development",
"company": "Cravy | GoCravy.com",
"city": "West Palm Beach",
"state": "FL",
"country": "US",
"formattedLocation": "West Palm Beach, FL",
"source": "Indeed",
"date": "Thu, 22 Oct 2015 04:19:25 GMT",
"snippet": "<b>Web</b> / App Development :. Experience developing APIs and <b>Web</b> Services. Experience with building multi-tier, multi-endpoint <b>web</b> applications....",
"url": "http://www.indeed.com/viewjob?jk=ac0ea7ce89d4bdd2&qd=_Eg2vwv-W7Xbq1qTFtzNjBoBOJ1n8jtnz2g86skcQrONeGbI_vQ-GttizbVSNLPf-ObBmLC0o-SFavhdY8sjrQA8LVfuFZ7NGBUNW0PNydwkt0LCVy_rQinuMfW47e_m&indpubnum=1588917421720308&atk=1a3j9gtcm5t9ldfh",
"onmousedown": "indeed_clk(this, '2655');",
"latitude": 26.714285,
"longitude": -80.04945,
"jobkey": "ac0ea7ce89d4bdd2",
"sponsored": false,
"expired": false,
"indeedApply": true,
"formattedLocationFull": "West Palm Beach, FL",
"formattedRelativeTime": "17 days ago"
},
{
"jobtitle": "Web Master- Software Developer vb vs2013+",
"company": "Boca Raton Regional Hospital",
"city": "Boca Raton",
"state": "FL",
"country": "US",
"formattedLocation": "Boca Raton, FL",
"source": "Boca Raton Regional Hospital",
"date": "Wed, 04 Nov 2015 06:23:00 GMT",
"snippet": "The <b>Web</b> Master-Software <b>Developer</b> is responsible for the Hospital website development, utilizing ASP.NET (vb.net) and MS SQL server....",
"url": "http://www.indeed.com/viewjob?jk=e04169c0bd508484&qd=_Eg2vwv-W7Xbq1qTFtzNjBoBOJ1n8jtnz2g86skcQrONeGbI_vQ-GttizbVSNLPf-ObBmLC0o-SFavhdY8sjrQA8LVfuFZ7NGBUNW0PNydwkt0LCVy_rQinuMfW47e_m&indpubnum=1588917421720308&atk=1a3j9gtcm5t9ldfh",
"onmousedown": "indeed_clk(this, '2655');",
"latitude": 26.343407,
"longitude": -80.07692,
"jobkey": "e04169c0bd508484",
"sponsored": false,
"expired": false,
"indeedApply": false,
"formattedLocationFull": "Boca Raton, FL 33427",
"formattedRelativeTime": "4 days ago"
},
{
"jobtitle": "IT Web/Portal Senior Architect",
"company": "Impact Business Group",
"city": "Jupiter",
"state": "FL",
"country": "US",
"formattedLocation": "Jupiter, FL",
"source": "Indeed",
"date": "Tue, 03 Nov 2015 16:47:55 GMT",
"snippet": "Deep experience with WCF <b>web</b> services and ASP.NET <b>Web</b> APIs. Sharepoint, <b>web</b> based solutions:. The IT <b>Web</b>/Portal Senior Architect will be responsible to lead a...",
"url": "http://www.indeed.com/viewjob?jk=523d48f7ba243b30&qd=_Eg2vwv-W7Xbq1qTFtzNjBoBOJ1n8jtnz2g86skcQrONeGbI_vQ-GttizbVSNLPf-ObBmLC0o-SFavhdY8sjrQA8LVfuFZ7NGBUNW0PNydwkt0LCVy_rQinuMfW47e_m&indpubnum=1588917421720308&atk=1a3j9gtcm5t9ldfh",
"onmousedown": "indeed_clk(this, '2655');",
"latitude": 26.934067,
"longitude": -80.09341,
"jobkey": "523d48f7ba243b30",
"sponsored": false,
"expired": false,
"indeedApply": true,
"formattedLocationFull": "Jupiter, FL",
"formattedRelativeTime": "4 days ago"
},
{
"jobtitle": "IT Web/Portal Senior Architect",
"company": "iMPact Business Group",
"city": "West Palm Beach",
"state": "FL",
"country": "US",
"formattedLocation": "West Palm Beach, FL",
"source": "Indeed",
"date": "Tue, 03 Nov 2015 14:31:25 GMT",
"snippet": "Deep experience with WCF <b>web</b> services and ASP.NET <b>Web</b> APIs. The IT <b>Web</b>/Portal Senior Architect will be responsible to lead a focused team of <b>Web</b> based...",
"url": "http://www.indeed.com/viewjob?jk=a4b2391e75d38d81&qd=_Eg2vwv-W7Xbq1qTFtzNjBoBOJ1n8jtnz2g86skcQrONeGbI_vQ-GttizbVSNLPf-ObBmLC0o-SFavhdY8sjrQA8LVfuFZ7NGBUNW0PNydwkt0LCVy_rQinuMfW47e_m&indpubnum=1588917421720308&atk=1a3j9gtcm5t9ldfh",
"onmousedown": "indeed_clk(this, '2655');",
"latitude": 26.714285,
"longitude": -80.04945,
"jobkey": "a4b2391e75d38d81",
"sponsored": false,
"expired": false,
"indeedApply": true,
"formattedLocationFull": "West Palm Beach, FL",
"formattedRelativeTime": "4 days ago"
},
{
"jobtitle": "Junior Java Developer",
"company": "LaunchCode",
"city": "Boca Raton",
"state": "FL",
"country": "US",
"formattedLocation": "Boca Raton, FL",
"source": "LaunchCode",
"date": "Tue, 03 Nov 2015 04:05:46 GMT",
"snippet": "Some experience in developing <b>web</b> applications using at least one popular <b>web</b> framework (JSF, Wicket, GWT, Spring MVC)....",
"url": "http://www.indeed.com/viewjob?jk=ab0ed7d6f7f5ef43&qd=_Eg2vwv-W7Xbq1qTFtzNjBoBOJ1n8jtnz2g86skcQrONeGbI_vQ-GttizbVSNLPf-ObBmLC0o-SFavhdY8sjrQA8LVfuFZ7NGBUNW0PNydwkt0LCVy_rQinuMfW47e_m&indpubnum=1588917421720308&atk=1a3j9gtcm5t9ldfh",
"onmousedown": "indeed_clk(this, '2655');",
"latitude": 26.357143,
"longitude": -80.08242,
"jobkey": "ab0ed7d6f7f5ef43",
"sponsored": false,
"expired": false,
"indeedApply": false,
"formattedLocationFull": "Boca Raton, FL",
"formattedRelativeTime": "5 days ago"
},
{
"jobtitle": "Junior Java Developer",
"company": "LaunchCode",
"city": "Palm Beach",
"state": "FL",
"country": "US",
"formattedLocation": "Palm Beach, FL",
"source": "LaunchCode",
"date": "Tue, 03 Nov 2015 04:05:44 GMT",
"snippet": "Some experience in developing <b>web</b> applications using at least one popular <b>web</b> framework (JSF, Wicket, GWT, Spring MVC)....",
"url": "http://www.indeed.com/viewjob?jk=97aa0e09e7f394bb&qd=_Eg2vwv-W7Xbq1qTFtzNjBoBOJ1n8jtnz2g86skcQrONeGbI_vQ-GttizbVSNLPf-ObBmLC0o-SFavhdY8sjrQA8LVfuFZ7NGBUNW0PNydwkt0LCVy_rQinuMfW47e_m&indpubnum=1588917421720308&atk=1a3j9gtcm5t9ldfh",
"onmousedown": "indeed_clk(this, '2655');",
"latitude": 26.703297,
"longitude": -80.03297,
"jobkey": "97aa0e09e7f394bb",
"sponsored": false,
"expired": false,
"indeedApply": false,
"formattedLocationFull": "Palm Beach, FL",
"formattedRelativeTime": "5 days ago"
},
{
"jobtitle": "Front End Web Developer",
"company": "Ikone International",
"city": "Miami",
"state": "FL",
"country": "US",
"formattedLocation": "Miami, FL",
"source": "Indeed",
"date": "Mon, 19 Oct 2015 00:49:18 GMT",
"snippet": "Front end <b>web</b> <b>developer</b>:. <b>Web</b> <b>developer</b>/programmer (Miami, FL). We are currently looking for an extremely experienced <b>web</b> designer/programmer to fill the...",
"url": "http://www.indeed.com/viewjob?jk=5ff77ef96eb7fe43&qd=_Eg2vwv-W7Xbq1qTFtzNjBoBOJ1n8jtnz2g86skcQrONeGbI_vQ-GttizbVSNLPf-ObBmLC0o-SFavhdY8sjrQA8LVfuFZ7NGBUNW0PNydwkt0LCVy_rQinuMfW47e_m&indpubnum=1588917421720308&atk=1a3j9gtcm5t9ldfh",
"onmousedown": "indeed_clk(this, '2655');",
"latitude": 25.89011,
"longitude": -80.17583,
"jobkey": "5ff77ef96eb7fe43",
"sponsored": false,
"expired": false,
"indeedApply": true,
"formattedLocationFull": "Miami, FL 33161",
"formattedRelativeTime": "20 days ago"
},
{
"jobtitle": "Progress Programmer",
"company": "PC Connection, Inc.",
"city": "Boca Raton",
"state": "FL",
"country": "US",
"formattedLocation": "Boca Raton, FL",
"source": "PC Connection",
"date": "Sat, 31 Oct 2015 18:51:21 GMT",
"snippet": "Experienced with OpenEdge/ABL and <b>Web</b> Services. Collaborating with other engineers, <b>developers</b>, analysts and business team members....",
"url": "http://www.indeed.com/viewjob?jk=bfe001307d4345e2&qd=_Eg2vwv-W7Xbq1qTFtzNjBoBOJ1n8jtnz2g86skcQrONeGbI_vQ-GttizbVSNLPf-ObBmLC0o-SFavhdY8sjrQA8LVfuFZ7NGBUNW0PNydwkt0LCVy_rQinuMfW47e_m&indpubnum=1588917421720308&atk=1a3j9gtcm5t9ldfh",
"onmousedown": "indeed_clk(this, '2655');",
"latitude": 26.381868,
"longitude": -80.0989,
"jobkey": "bfe001307d4345e2",
"sponsored": false,
"expired": false,
"indeedApply": false,
"formattedLocationFull": "Boca Raton, FL 33431",
"formattedRelativeTime": "7 days ago"
},
{
"jobtitle": "Mobile Software Engineer",
"company": "Fractl",
"city": "Delray Beach",
"state": "FL",
"country": "US",
"formattedLocation": "Delray Beach, FL",
"source": "Fractl",
"date": "Wed, 21 Oct 2015 21:57:12 GMT",
"snippet": "Knowledge of other <b>web</b> technologies and UI/UX standards. We nurture a diverse team of strategists, <b>developers</b>, designers, animators, journalists, search experts...",
"url": "http://www.indeed.com/viewjob?jk=34ebe2123da0cea2&qd=_Eg2vwv-W7Xbq1qTFtzNjBoBOJ1n8jtnz2g86skcQrONeGbI_vQ-GttizbVSNLPf-ObBmLC0o-SFavhdY8sjrQA8LVfuFZ7NGBUNW0PNydwkt0LCVy_rQinuMfW47e_m&indpubnum=1588917421720308&atk=1a3j9gtcm5t9ldfh",
"onmousedown": "indeed_clk(this, '2655');",
"latitude": 26.458792,
"longitude": -80.07143,
"jobkey": "34ebe2123da0cea2",
"sponsored": false,
"expired": false,
"indeedApply": true,
"formattedLocationFull": "Delray Beach, FL",
"formattedRelativeTime": "17 days ago"
},
{
"jobtitle": "Junior Java Developer",
"company": "LaunchCode",
"city": "Fort Lauderdale",
"state": "FL",
"country": "US",
"formattedLocation": "Fort Lauderdale, FL",
"source": "LaunchCode",
"date": "Tue, 03 Nov 2015 04:05:43 GMT",
"snippet": "Some experience in developing <b>web</b> applications using at least one popular <b>web</b> framework (JSF, Wicket, GWT, Spring MVC)....",
"url": "http://www.indeed.com/viewjob?jk=5a9b14a18274665c&qd=_Eg2vwv-W7Xbq1qTFtzNjBoBOJ1n8jtnz2g86skcQrONeGbI_vQ-GttizbVSNLPf-ObBmLC0o-SFavhdY8sjrQA8LVfuFZ7NGBUNW0PNydwkt0LCVy_rQinuMfW47e_m&indpubnum=1588917421720308&atk=1a3j9gtcm5t9ldfh",
"onmousedown": "indeed_clk(this, '2655');",
"latitude": 26.120878,
"longitude": -80.14286,
"jobkey": "5a9b14a18274665c",
"sponsored": false,
"expired": false,
"indeedApply": false,
"formattedLocationFull": "Fort Lauderdale, FL",
"formattedRelativeTime": "5 days ago"
},
{
"jobtitle": "Front End Developer",
"company": "RingCentral",
"city": "Boca Raton",
"state": "FL",
"country": "US",
"formattedLocation": "Boca Raton, FL",
"source": "RingCentral",
"date": "Fri, 23 Oct 2015 15:58:00 GMT",
"snippet": "Front End <b>Developer</b>. 3+ years’ experience building world class, public facing <b>web</b> applications. Experience scaling and improving performance on evolving...",
"url": "http://www.indeed.com/viewjob?jk=3f8f0da463a64c3a&qd=_Eg2vwv-W7Xbq1qTFtzNjBoBOJ1n8jtnz2g86skcQrONeGbI_vQ-GttizbVSNLPf-ObBmLC0o-SFavhdY8sjrQA8LVfuFZ7NGBUNW0PNydwkt0LCVy_rQinuMfW47e_m&indpubnum=1588917421720308&atk=1a3j9gtcm5t9ldfh",
"onmousedown": "indeed_clk(this, '2655');",
"latitude": 26.357143,
"longitude": -80.08242,
"jobkey": "3f8f0da463a64c3a",
"sponsored": false,
"expired": false,
"indeedApply": false,
"formattedLocationFull": "Boca Raton, FL",
"formattedRelativeTime": "15 days ago"
},
{
"jobtitle": "Full Stack Rails Developer",
"company": "Playwire Media",
"city": "Deerfield Beach",
"state": "FL",
"country": "US",
"formattedLocation": "Deerfield Beach, FL",
"source": "Indeed",
"date": "Wed, 28 Oct 2015 19:31:49 GMT",
"snippet": "Full Stack Rails <b>Developer</b>:. Experience with video for the <b>web</b>, particularly HTML5 video. Playwire Media seeks a Ruby on Rails <b>developer</b> to help build new...",
"url": "http://www.indeed.com/viewjob?jk=8b06f3227247c5df&qd=_Eg2vwv-W7Xbq1qTFtzNjBoBOJ1n8jtnz2g86skcQrONeGbI_vQ-GttizbVSNLPf-ObBmLC0o-SFavhdY8sjrQA8LVfuFZ7NGBUNW0PNydwkt0LCVy_rQinuMfW47e_m&indpubnum=1588917421720308&atk=1a3j9gtcm5t9ldfh",
"onmousedown": "indeed_clk(this, '2655');",
"latitude": 26.315933,
"longitude": -80.0989,
"jobkey": "8b06f3227247c5df",
"sponsored": false,
"expired": false,
"indeedApply": true,
"formattedLocationFull": "Deerfield Beach, FL",
"formattedRelativeTime": "10 days ago"
},
{
"jobtitle": "Senior Web Application Developer - Miami, FL",
"company": "UnitedHealth Group",
"city": "Miami",
"state": "FL",
"country": "US",
"formattedLocation": "Miami, FL",
"source": "UnitedHealth Group",
"date": "Wed, 28 Oct 2015 01:31:00 GMT",
"snippet": "5+ years of experience working as a <b>Web</b> Applications <b>developer</b>. <b>Web</b> Sites Development Experience. Here, at UHC South Florida, you have the opportunity to...",
"url": "http://www.indeed.com/viewjob?jk=ee064e7f18ff7276&qd=_Eg2vwv-W7Xbq1qTFtzNjBoBOJ1n8jtnz2g86skcQrONeGbI_vQ-GttizbVSNLPf-ObBmLC0o-SFavhdY8sjrQA8LVfuFZ7NGBUNW0PNydwkt0LCVy_rQinuMfW47e_m&indpubnum=1588917421720308&atk=1a3j9gtcm5t9ldfh",
"onmousedown": "indeed_clk(this, '2655');",
"latitude": 25.771978,
"longitude": -80.19231,
"jobkey": "ee064e7f18ff7276",
"sponsored": false,
"expired": false,
"indeedApply": false,
"formattedLocationFull": "Miami, FL",
"formattedRelativeTime": "11 days ago"
},
{
"jobtitle": "Project Manager – Technical",
"company": "Altimetrik Corporation",
"city": "Miami",
"state": "FL",
"country": "US",
"formattedLocation": "Miami, FL",
"source": "Indeed",
"date": "Mon, 02 Nov 2015 17:22:20 GMT",
"snippet": "Experience in *interfacing with the offshore teams, <b>developers</b>, customers and manage Delivery*. Altimetrik today is a rapidly growing organization with more...",
"url": "http://www.indeed.com/viewjob?jk=e6432b14a2dcefc7&qd=_Eg2vwv-W7Xbq1qTFtzNjBoBOJ1n8jtnz2g86skcQrONeGbI_vQ-GttizbVSNLPf-ObBmLC0o-SFavhdY8sjrQA8LVfuFZ7NGBUNW0PNydwkt0LCVy_rQinuMfW47e_m&indpubnum=1588917421720308&atk=1a3j9gtcm5t9ldfh",
"onmousedown": "indeed_clk(this, '2655');",
"latitude": 25.771978,
"longitude": -80.19231,
"jobkey": "e6432b14a2dcefc7",
"sponsored": false,
"expired": false,
"indeedApply": true,
"formattedLocationFull": "Miami, FL",
"formattedRelativeTime": "5 days ago"
},
{
"jobtitle": "Web Developer (Within 40 Miles of Jupiter, Florida Only)",
"company": "Jupiter Techs",
"city": "Jupiter",
"state": "FL",
"country": "US",
"formattedLocation": "Jupiter, FL",
"source": "Indeed",
"date": "Mon, 26 Oct 2015 13:45:36 GMT",
"snippet": "<b>Web</b> <b>Developer</b> Job Responsibilities:. <b>Web</b> <b>Developer</b> Skills and Qualifications:. Wordpress, PHP, C#, JavaScript, JQuery, HTML, HTML5, CSS, CSS3, E-Commerce, <b>Web</b>...",
"url": "http://www.indeed.com/viewjob?jk=56fb9079e87f9b96&qd=_Eg2vwv-W7Xbq1qTFtzNjBoBOJ1n8jtnz2g86skcQrONeGbI_vQ-GttizbVSNLPf-ObBmLC0o-SFavhdY8sjrQA8LVfuFZ7NGBUNW0PNydwkt0LCVy_rQinuMfW47e_m&indpubnum=1588917421720308&atk=1a3j9gtcm5t9ldfh",
"onmousedown": "indeed_clk(this, '2655');",
"latitude": 26.92033,
"longitude": -80.07143,
"jobkey": "56fb9079e87f9b96",
"sponsored": false,
"expired": false,
"indeedApply": true,
"formattedLocationFull": "Jupiter, FL 33477",
"formattedRelativeTime": "12 days ago"
}
];

var jobs = [];
for(var i = 0; i < topics.length; i++) {
  var data = [
    { name : 'jobtitle', val : topics[i].jobtitle },
    { name : 'company', val : topics[i].company },
    { name : 'date', val : topics[i].date },
    { name : 'snippet', val : topics[i].snippet },
    { name : 'url', val : topics[i].url },
    { name : 'city', val : 'Miami' },   // get city from API URL since Indeed gives "subcities" for "city";
    { name : 'latitude', val : topics[i].latitude },
    { name : 'longitude', val : topics[i].longitude }
  ];
  jobs[i] = data;
}

module.exports = jobs;      // COMPUTE SALARY AND # OF JOBS PER CITY PER JOB CATEGORY BY AVERAGING SALARIES FOR CURRENT JOB LISTINGS;

// http://api.indeed.com/ads/apisearch?publisher=1588917421720308&co=us&format=json&fromage=90&jt=fulltime&l=miami%2Cfl&latlong=1&limit=50&q=web+developer&radius=50&st=employer&useragent=&userip=0.0.0.0&v=2
// set st=employer so map markers don't overlap and duplicates are not shown; "limit" is returned, so see "totalResults" field for total listings;